### ISSUE TITLE
Shared test args

### ISSUE THREAD

**Issue by alex-semenk** [kajf/bozr#68]
Currently tool provides ability to declare arguments for each call separately.
The enhancement is to add args to the test level, so they could be shared between calls.
This should help to organize tests in a better way and avoid args duplications. 

Example:
```javascript
[
  {
    "name": "TestName",
    "args": {
      "arg1": "foo",
      "arg2": "bar"
    },
    "calls": [ ]
  }
]
```

**Comment by kajf** [comment]
Currently arguments (as well as remember vars) could be referenced across multiple calls, so sharing requirement is covered. As for var duplication, there is a separate check (since 0.9.1) that marks test as failed in case duplicated vars are met.

So currently in a nutshell this issue is only about moving args section one level higher in json which is reasonable in some cases but given this is a breaking format change and could be confusing in some cases, it does not seem to worth the effort.

**Comment by alex-semenk** [comment]
Agree, moving args one level higher could be confusing in some cases and certainly would be a breaking change. How about not moving args, but adding it on one level higher. So we could use both variables - one on the test case level and one on the call level if necessary.

The real case is: As a user I wan't to use a single account and object id over all test calls.

**Comment by kajf** [comment]
Your real case is covered if you just declare common args in first call of the test

I don't think it is good from clarity and consistency standpoint if we allow args on different levels

**Comment by dpfg** [comment]
@kajf I wouldn't agree. It's not obvious that args from first call are shared for all. Would be much more clear if they would be on top of all calls.

**Comment by kajf** [comment]
@dpfg 
The problem with declaring ALL args on top is that sometimes you need arg only in 3rd call, so you want it close the the place where it is used. Think about scenario tests where test contains 5-7 calls
Do we want to encourage large section on top with all args for all calls?

As for clarity, 
bear in mind there is a 'remember' section that follows the same rules of sharing variable with following calls, so this is kind of intuitive that args share the same logic

**Comment by dpfg** [comment]
@kajf we could support both places. closer to call and more wide for entire test.
